Improvements in Site : Check Comments
ElixirTechCommunity/Nexus_Website pull request #36
Opened 2022-08-19 15:49 UTC by RamGoel

1- Made About Page (https://github.com/ElixirTechCommunity/Nexus_Website/issues/29)
2- Added Glassmorphism (https://github.com/ElixirTechCommunity/Nexus_Website/issues/27)
3- Added Social Links in Header (https://github.com/ElixirTechCommunity/Nexus_Website/issues/32)
4- CTA button Updated (https://github.com/ElixirTechCommunity/Nexus_Website/issues/26)
5- Smooth Scroll Done (https://github.com/ElixirTechCommunity/Nexus_Website/issues/30)

2022-08-19 16:15 UTC, pulkit-30 commented
Dev Preview : https://deploy-preview-36--hacknexus.netlify.app/dev.html

2022-08-19 16:20 UTC, pulkit-30 requested changes

2022-08-19 16:20 UTC, pulkit-30 commented on scripts/vanilla-tilt.js
> +var VanillaTilt = (function () {
This effect is done in #34

2022-08-19 16:24 UTC, Anv3sh commented on scripts/vanilla-tilt.js
> +var VanillaTilt = (function () {
@RamGoel  can you please revert this commit else we will face a merge conflict.

2022-08-19 16:30 UTC, Anv3sh requested changes

2022-08-19 16:30 UTC, Anv3sh commented on dev.html
> +        <a class="headLinks" href="https://www.instagram.com/nexus_whatthehack/"><i
You don't need to change the structure of the codebase just add the links in the `href` . The class names are defined for a reason don't change them for your convenience.

2022-08-19 16:41 UTC, RamGoel commented
Made Required Changes

2022-08-19 16:43 UTC, RamGoel commented
@pulkit-30 @Anv3sh Check Now

2022-08-19 17:49 UTC, dewank07 requested changes
also revert back the changes done in stylesheets/slide_page.css for glassmorphism they are already did in #34

2022-08-19 18:17 UTC, Anv3sh commented
@RamGoel please resolve the merge conflict.

2022-08-20 17:00 UTC, RamGoel commented
@Anv3sh @pulkit-30 Check Now

2022-08-21 07:45 UTC, closed without merging