Added social links in header
ElixirTechCommunity/Nexus_Website pull request #37
Opened 2022-08-19 18:02 UTC by gautmikhanna

2022-08-19 19:06 UTC, pulkit-30 commented
🫤

<img width="1669" alt="Screenshot 2022-08-20 at 12 35 56 AM" src="https://user-images.githubusercontent.com/76155456/185689738-e2577d57-9a9d-4d95-a209-aeaaeb7c338f.png">

2022-08-19 19:09 UTC, pulkit-30 requested changes

2022-08-19 19:09 UTC, pulkit-30 commented on dev.html
> +          <a href="https://discord.gg/RHn4CPuW" target="_blank"
LGTM 🎉 , only see discord invitation link @gautmikhanna

2022-08-20 09:50 UTC, dewank07 commented
https://discord.gg/R53QVZJ2fn  use this link as we will be redirecting the audience to Elixir server already

2022-08-21 06:13 UTC, Anv3sh approved these changes
Changed the discord link looks good 👍🏻

2022-08-21 06:15 UTC, Anv3sh commented on dev.html
> +          <a href="https://discord.gg/RHn4CPuW" target="_blank"
Fixed it. 👍🏻

2022-08-21 06:15 UTC, merged