Improvements : Added Arrow FAQ and Logo Footer
ElixirTechCommunity/Nexus_Website pull request #85
Opened 2022-09-03 09:44 UTC by RamGoel

Fixes #83

2022-09-04 15:06 UTC, pulkit-30 requested changes

2022-09-04 15:06 UTC, pulkit-30 commented on dev/styles/faqPage.css
> -  font-family: Poppins !important;
Is this right way....??? 
Not working for me, can you please verify this

2022-09-04 15:06 UTC, pulkit-30 commented on dev/styles/faqPage.css
> +  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-
Instead can we use font-awsm 

```
<i class="fa-sharp fa-solid fa-caret-down"></i>
```

2022-09-04 15:06 UTC, pulkit-30 commented on dev/styles/footer.css
> +  /* width: 80% !important; */
Please, remove extra comment lines

2022-09-04 15:06 UTC, pulkit-30 commented on dev/index.html
> +    />
For what?

2022-09-04 15:06 UTC, pulkit-30 commented on dev/index.html
> +              <li class="">
Please remove `class="" `

2022-09-04 15:06 UTC, pulkit-30 commented on dev/index.html
> +      <img src="./assets/gfgLogo.png" class="footerLogo " />
Add alt attribute

2022-09-04 15:07 UTC, pulkit-30 commented
<img width="1679" alt="Screenshot 2022-09-04 at 8 36 53 PM" src="https://user-images.githubusercontent.com/76155456/188320337-10d481ba-29b9-4fc4-b769-d2017438c782.png">

Please increase some height of the this section

2022-09-07 15:59 UTC, RamGoel commented on dev/styles/faqPage.css
> +  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-
As we have used bootstrap accordions, it adds a down arrow by default, but the colour of the arrow doesn't match the background, so this has been done to change the colour.

2022-09-08 06:08 UTC, RamGoel commented
@pulkit-30 @dewank07 Check if everything Okay.

2022-09-08 06:10 UTC, pulkit-30 commented on dev/styles/faqPage.css
> -  font-family: Poppins !important;
@RamGoel mind having a look at this

2022-09-08 13:40 UTC, RamGoel commented on dev/styles/faqPage.css
> -  font-family: Poppins !important;
It is supposed to work now, working on my side. Confirm, please. @dewank07 @Anv3sh

2022-09-10 11:22 UTC, pulkit-30 approved these changes
GTG 🚀

2022-09-10 11:22 UTC, merged